# Generated by Django 6.0.6 on 2026-06-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surgeryrequest",
            name="duration",
        ),
    ]
