services:
  postgres:
    image: postgres:16
    container_name: hospital-postgres
    restart: always
    environment:
      POSTGRES_DB: hospital_scheduler_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
    ports:
      - "5432:5432"
    volumes:
      - hospital_postgres_data:/var/lib/postgresql/data

volumes:
  hospital_postgres_data: