# Generated by Django 6.0.6 on 2026-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_remove_surgeryrequest_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="day_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
