# Generated by Django 6.0.6 on 2026-07-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_scheduleitem_day_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleplan",
            name="anesthesia_balance_penalty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="day_balance_penalty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="priority_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="room_idle_penalty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="success_rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="surgeon_idle_penalty",
            field=models.IntegerField(default=0),
        ),
    ]
