# Generated by Django 6.0.6 on 2026-07-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0006_rename_simulation_result_scheduleplan_simulation_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleplan",
            name="score_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scheduleplan",
            name="weight_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
