# Generated by Django 6.0.6 on 2026-07-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0007_scheduleplan_score_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgerytype",
            name="priority",
            field=models.CharField(
                choices=[
                    ("critical", "Kritik"),
                    ("high", "Yüksek"),
                    ("medium", "Orta"),
                    ("low", "Düşük"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
